/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthUser,
  Batch,
  BatchStatusUpdate,
  CommitmentRequest,
  CreateCommitmentRequest,
  CreateLead,
  CreateOrder,
  Error,
  FarmerReceipt,
  HealthStatus,
  Lead,
  Lot,
  Message,
  Order,
  OrderStatusUpdate,
  PhoneRequest,
  VerifyOtp
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: Parameters<typeof customFetch>[1]): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getListBatchesUrl = () => {




  return `/api/batches`
}

/**
 * Returns Digital Product Passport batches, newest first.
 * @summary List batches
 */
export const listBatches = async ( options?: Parameters<typeof customFetch>[1]): Promise<Batch[]> => {

  return customFetch<Batch[]>(getListBatchesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBatchesQueryKey = () => {
    return [
    `/api/batches`
    ] as const;
    }


export const getListBatchesQueryOptions = <TData = Awaited<ReturnType<typeof listBatches>>, TError = ErrorType<Error>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBatches>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBatchesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBatches>>> = ({ signal }) => listBatches({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBatches>>, TError, TData> & { queryKey: QueryKey }
}

export type ListBatchesQueryResult = NonNullable<Awaited<ReturnType<typeof listBatches>>>
export type ListBatchesQueryError = ErrorType<Error>


/**
 * @summary List batches
 */

export function useListBatches<TData = Awaited<ReturnType<typeof listBatches>>, TError = ErrorType<Error>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBatches>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListBatchesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetBatchUrl = (passportId: string,) => {




  return `/api/batches/${passportId}`
}

/**
 * @summary Get a public batch passport
 */
export const getBatch = async (passportId: string, options?: Parameters<typeof customFetch>[1]): Promise<Batch> => {

  return customFetch<Batch>(getGetBatchUrl(passportId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBatchQueryKey = (passportId: string,) => {
    return [
    `/api/batches/${passportId}`
    ] as const;
    }


export const getGetBatchQueryOptions = <TData = Awaited<ReturnType<typeof getBatch>>, TError = ErrorType<Error>>(passportId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBatch>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBatchQueryKey(passportId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBatch>>> = ({ signal }) => getBatch(passportId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: passportId !== null && passportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBatch>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBatchQueryResult = NonNullable<Awaited<ReturnType<typeof getBatch>>>
export type GetBatchQueryError = ErrorType<Error>


/**
 * @summary Get a public batch passport
 */

export function useGetBatch<TData = Awaited<ReturnType<typeof getBatch>>, TError = ErrorType<Error>>(
 passportId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBatch>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBatchQueryOptions(passportId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetFarmerReceiptUrl = (batchId: number,) => {




  return `/api/batches/id/${batchId}`
}

/**
 * @summary Get a public farmer payment receipt
 */
export const getFarmerReceipt = async (batchId: number, options?: Parameters<typeof customFetch>[1]): Promise<FarmerReceipt> => {

  return customFetch<FarmerReceipt>(getGetFarmerReceiptUrl(batchId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFarmerReceiptQueryKey = (batchId: number,) => {
    return [
    `/api/batches/id/${batchId}`
    ] as const;
    }


export const getGetFarmerReceiptQueryOptions = <TData = Awaited<ReturnType<typeof getFarmerReceipt>>, TError = ErrorType<Error>>(batchId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFarmerReceipt>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFarmerReceiptQueryKey(batchId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFarmerReceipt>>> = ({ signal }) => getFarmerReceipt(batchId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: batchId !== null && batchId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFarmerReceipt>>, TError, TData> & { queryKey: QueryKey }
}

export type GetFarmerReceiptQueryResult = NonNullable<Awaited<ReturnType<typeof getFarmerReceipt>>>
export type GetFarmerReceiptQueryError = ErrorType<Error>


/**
 * @summary Get a public farmer payment receipt
 */

export function useGetFarmerReceipt<TData = Awaited<ReturnType<typeof getFarmerReceipt>>, TError = ErrorType<Error>>(
 batchId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFarmerReceipt>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetFarmerReceiptQueryOptions(batchId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getUpdateBatchStatusUrl = (passportId: string,) => {




  return `/api/batches/${passportId}/status`
}

/**
 * @summary Update an assigned batch status
 */
export const updateBatchStatus = async (passportId: string,
    batchStatusUpdate: BatchStatusUpdate, options?: Parameters<typeof customFetch>[1]): Promise<Batch> => {

  return customFetch<Batch>(getUpdateBatchStatusUrl(passportId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(batchStatusUpdate)
  }
);}





export const getUpdateBatchStatusMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBatchStatus>>, TError,{passportId: string;data: BodyType<BatchStatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBatchStatus>>, TError,{passportId: string;data: BodyType<BatchStatusUpdate>}, TContext> => {

const mutationKey = ['updateBatchStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBatchStatus>>, {passportId: string;data: BodyType<BatchStatusUpdate>}> = (props) => {
          const {passportId,data} = props ?? {};

          return  updateBatchStatus(passportId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateBatchStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateBatchStatus>>>
    export type UpdateBatchStatusMutationBody = BodyType<BatchStatusUpdate>
    export type UpdateBatchStatusMutationError = ErrorType<Error>

    /**
 * @summary Update an assigned batch status
 */
export const useUpdateBatchStatus = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBatchStatus>>, TError,{passportId: string;data: BodyType<BatchStatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateBatchStatus>>,
        TError,
        {passportId: string;data: BodyType<BatchStatusUpdate>},
        TContext
      > => {
      return useMutation(getUpdateBatchStatusMutationOptions(options));
    }

export const getListLotsUrl = () => {




  return `/api/lots`
}

/**
 * @summary List public marketplace lots
 */
export const listLots = async ( options?: Parameters<typeof customFetch>[1]): Promise<Lot[]> => {

  return customFetch<Lot[]>(getListLotsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListLotsQueryKey = () => {
    return [
    `/api/lots`
    ] as const;
    }


export const getListLotsQueryOptions = <TData = Awaited<ReturnType<typeof listLots>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLots>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLotsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLots>>> = ({ signal }) => listLots({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLots>>, TError, TData> & { queryKey: QueryKey }
}

export type ListLotsQueryResult = NonNullable<Awaited<ReturnType<typeof listLots>>>
export type ListLotsQueryError = ErrorType<unknown>


/**
 * @summary List public marketplace lots
 */

export function useListLots<TData = Awaited<ReturnType<typeof listLots>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLots>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListLotsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetLotUrl = (lotId: string,) => {




  return `/api/lots/${lotId}`
}

/**
 * @summary Get a public marketplace lot
 */
export const getLot = async (lotId: string, options?: Parameters<typeof customFetch>[1]): Promise<Lot> => {

  return customFetch<Lot>(getGetLotUrl(lotId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLotQueryKey = (lotId: string,) => {
    return [
    `/api/lots/${lotId}`
    ] as const;
    }


export const getGetLotQueryOptions = <TData = Awaited<ReturnType<typeof getLot>>, TError = ErrorType<Error>>(lotId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLot>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLotQueryKey(lotId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLot>>> = ({ signal }) => getLot(lotId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: lotId !== null && lotId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLot>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLotQueryResult = NonNullable<Awaited<ReturnType<typeof getLot>>>
export type GetLotQueryError = ErrorType<Error>


/**
 * @summary Get a public marketplace lot
 */

export function useGetLot<TData = Awaited<ReturnType<typeof getLot>>, TError = ErrorType<Error>>(
 lotId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLot>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLotQueryOptions(lotId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateCommitmentRequestUrl = () => {




  return `/api/commitment-requests`
}

/**
 * @summary Submit a pre-season volume commitment
 */
export const createCommitmentRequest = async (createCommitmentRequest: CreateCommitmentRequest, options?: Parameters<typeof customFetch>[1]): Promise<CommitmentRequest> => {

  return customFetch<CommitmentRequest>(getCreateCommitmentRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCommitmentRequest)
  }
);}





export const getCreateCommitmentRequestMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCommitmentRequest>>, TError,{data: BodyType<CreateCommitmentRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCommitmentRequest>>, TError,{data: BodyType<CreateCommitmentRequest>}, TContext> => {

const mutationKey = ['createCommitmentRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCommitmentRequest>>, {data: BodyType<CreateCommitmentRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createCommitmentRequest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCommitmentRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createCommitmentRequest>>>
    export type CreateCommitmentRequestMutationBody = BodyType<CreateCommitmentRequest>
    export type CreateCommitmentRequestMutationError = ErrorType<unknown>

    /**
 * @summary Submit a pre-season volume commitment
 */
export const useCreateCommitmentRequest = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCommitmentRequest>>, TError,{data: BodyType<CreateCommitmentRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCommitmentRequest>>,
        TError,
        {data: BodyType<CreateCommitmentRequest>},
        TContext
      > => {
      return useMutation(getCreateCommitmentRequestMutationOptions(options));
    }

export const getListOrdersUrl = () => {




  return `/api/orders`
}

/**
 * @summary List buyer order requests
 */
export const listOrders = async ( options?: Parameters<typeof customFetch>[1]): Promise<Order[]> => {

  return customFetch<Order[]>(getListOrdersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListOrdersQueryKey = () => {
    return [
    `/api/orders`
    ] as const;
    }


export const getListOrdersQueryOptions = <TData = Awaited<ReturnType<typeof listOrders>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listOrders>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOrdersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOrders>>> = ({ signal }) => listOrders({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listOrders>>, TError, TData> & { queryKey: QueryKey }
}

export type ListOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof listOrders>>>
export type ListOrdersQueryError = ErrorType<unknown>


/**
 * @summary List buyer order requests
 */

export function useListOrders<TData = Awaited<ReturnType<typeof listOrders>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listOrders>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListOrdersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getCreateOrderUrl = () => {




  return `/api/orders`
}

/**
 * @summary Request some or all of a marketplace lot
 */
export const createOrder = async (createOrder: CreateOrder, options?: Parameters<typeof customFetch>[1]): Promise<Order> => {

  return customFetch<Order>(getCreateOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrder)
  }
);}





export const getCreateOrderMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: BodyType<CreateOrder>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: BodyType<CreateOrder>}, TContext> => {

const mutationKey = ['createOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrder>>, {data: BodyType<CreateOrder>}> = (props) => {
          const {data} = props ?? {};

          return  createOrder(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createOrder>>>
    export type CreateOrderMutationBody = BodyType<CreateOrder>
    export type CreateOrderMutationError = ErrorType<Error>

    /**
 * @summary Request some or all of a marketplace lot
 */
export const useCreateOrder = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: BodyType<CreateOrder>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createOrder>>,
        TError,
        {data: BodyType<CreateOrder>},
        TContext
      > => {
      return useMutation(getCreateOrderMutationOptions(options));
    }

export const getUpdateOrderStatusUrl = (orderId: number,) => {




  return `/api/orders/${orderId}/status`
}

/**
 * @summary Confirm, reject, or deliver an order
 */
export const updateOrderStatus = async (orderId: number,
    orderStatusUpdate: OrderStatusUpdate, options?: Parameters<typeof customFetch>[1]): Promise<Order> => {

  return customFetch<Order>(getUpdateOrderStatusUrl(orderId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(orderStatusUpdate)
  }
);}





export const getUpdateOrderStatusMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderStatus>>, TError,{orderId: number;data: BodyType<OrderStatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrderStatus>>, TError,{orderId: number;data: BodyType<OrderStatusUpdate>}, TContext> => {

const mutationKey = ['updateOrderStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrderStatus>>, {orderId: number;data: BodyType<OrderStatusUpdate>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  updateOrderStatus(orderId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrderStatus>>>
    export type UpdateOrderStatusMutationBody = BodyType<OrderStatusUpdate>
    export type UpdateOrderStatusMutationError = ErrorType<unknown>

    /**
 * @summary Confirm, reject, or deliver an order
 */
export const useUpdateOrderStatus = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderStatus>>, TError,{orderId: number;data: BodyType<OrderStatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateOrderStatus>>,
        TError,
        {orderId: number;data: BodyType<OrderStatusUpdate>},
        TContext
      > => {
      return useMutation(getUpdateOrderStatusMutationOptions(options));
    }

export const getCreateLeadUrl = () => {




  return `/api/leads`
}

/**
 * @summary Capture a landing-page lead
 */
export const createLead = async (createLead: CreateLead, options?: Parameters<typeof customFetch>[1]): Promise<Lead> => {

  return customFetch<Lead>(getCreateLeadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLead)
  }
);}





export const getCreateLeadMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLead>>, TError,{data: BodyType<CreateLead>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createLead>>, TError,{data: BodyType<CreateLead>}, TContext> => {

const mutationKey = ['createLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLead>>, {data: BodyType<CreateLead>}> = (props) => {
          const {data} = props ?? {};

          return  createLead(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateLeadMutationResult = NonNullable<Awaited<ReturnType<typeof createLead>>>
    export type CreateLeadMutationBody = BodyType<CreateLead>
    export type CreateLeadMutationError = ErrorType<Error>

    /**
 * @summary Capture a landing-page lead
 */
export const useCreateLead = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLead>>, TError,{data: BodyType<CreateLead>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createLead>>,
        TError,
        {data: BodyType<CreateLead>},
        TContext
      > => {
      return useMutation(getCreateLeadMutationOptions(options));
    }

export const getAuthRequestOtpUrl = () => {




  return `/api/auth/request-otp`
}

/**
 * @summary Request an operator OTP
 */
export const authRequestOtp = async (phoneRequest: PhoneRequest, options?: Parameters<typeof customFetch>[1]): Promise<Message> => {

  return customFetch<Message>(getAuthRequestOtpUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(phoneRequest)
  }
);}





export const getAuthRequestOtpMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRequestOtp>>, TError,{data: BodyType<PhoneRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authRequestOtp>>, TError,{data: BodyType<PhoneRequest>}, TContext> => {

const mutationKey = ['authRequestOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRequestOtp>>, {data: BodyType<PhoneRequest>}> = (props) => {
          const {data} = props ?? {};

          return  authRequestOtp(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthRequestOtpMutationResult = NonNullable<Awaited<ReturnType<typeof authRequestOtp>>>
    export type AuthRequestOtpMutationBody = BodyType<PhoneRequest>
    export type AuthRequestOtpMutationError = ErrorType<Error>

    /**
 * @summary Request an operator OTP
 */
export const useAuthRequestOtp = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authRequestOtp>>, TError,{data: BodyType<PhoneRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authRequestOtp>>,
        TError,
        {data: BodyType<PhoneRequest>},
        TContext
      > => {
      return useMutation(getAuthRequestOtpMutationOptions(options));
    }

export const getAuthVerifyOtpUrl = () => {




  return `/api/auth/verify-otp`
}

/**
 * @summary Verify an OTP and create a session
 */
export const authVerifyOtp = async (verifyOtp: VerifyOtp, options?: Parameters<typeof customFetch>[1]): Promise<AuthUser> => {

  return customFetch<AuthUser>(getAuthVerifyOtpUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyOtp)
  }
);}





export const getAuthVerifyOtpMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authVerifyOtp>>, TError,{data: BodyType<VerifyOtp>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authVerifyOtp>>, TError,{data: BodyType<VerifyOtp>}, TContext> => {

const mutationKey = ['authVerifyOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authVerifyOtp>>, {data: BodyType<VerifyOtp>}> = (props) => {
          const {data} = props ?? {};

          return  authVerifyOtp(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthVerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof authVerifyOtp>>>
    export type AuthVerifyOtpMutationBody = BodyType<VerifyOtp>
    export type AuthVerifyOtpMutationError = ErrorType<Error>

    /**
 * @summary Verify an OTP and create a session
 */
export const useAuthVerifyOtp = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authVerifyOtp>>, TError,{data: BodyType<VerifyOtp>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authVerifyOtp>>,
        TError,
        {data: BodyType<VerifyOtp>},
        TContext
      > => {
      return useMutation(getAuthVerifyOtpMutationOptions(options));
    }

export const getAuthMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary Get the authenticated operator
 */
export const authMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<AuthUser> => {

  return customFetch<AuthUser>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuthMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<Error>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) => authMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>
export type AuthMeQueryError = ErrorType<Error>


/**
 * @summary Get the authenticated operator
 */

export function useAuthMe<TData = Awaited<ReturnType<typeof authMe>>, TError = ErrorType<Error>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getAuthLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary Clear the operator session
 */
export const authLogout = async ( options?: Parameters<typeof customFetch>[1]): Promise<Message> => {

  return customFetch<Message>(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAuthLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {


          return  authLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>

    export type AuthLogoutMutationError = ErrorType<unknown>

    /**
 * @summary Clear the operator session
 */
export const useAuthLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthLogoutMutationOptions(options));
    }

